# Site settings
title: FPLB
description: Functional Programming in Long Beach
keywords: FP , functional programming, long beach, lisp, haskell, clojure, code, meetup, usergroup
author: karim amer , David Nuon
baseurl: "/" # the subpath of your site, e.g. /blog/
domain_name: 'http://www.fplongbeach.com/'
markdown: redcarpet
highlighter: pygments
paginate: 20
